#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "platform/capabilities.json"
OUTPUT = ROOT / "docs/AUTO_CAPABILITIES.md"


def render(data: dict) -> str:
    lines = [
        "# Auto-generated capability index",
        "",
        "> Generated by `tools/autodoc.py` from `platform/capabilities.json`. Do not hand-edit.",
        "",
    ]
    for category in sorted(data["categories"]):
        lines.extend(
            [
                f"## {category}",
                "",
                "| Capability | Status | Contract |",
                "|---|---|---|",
            ]
        )
        entries = sorted(data["categories"][category], key=lambda item: item["name"].lower())
        for item in entries:
            lines.append(f"| {item['name']} | `{item['status']}` | {item['detail']} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            print("ERROR: docs/AUTO_CAPABILITIES.md is stale; run python tools/autodoc.py")
            return 2
        print("PASS: auto-documentation is current")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"WROTE: {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
